/*
** LatLongLine.h - Pure abstract interface for lines that are overlaid on
**	surface generated by engines. Subclass this with toolkit specific implementations
**	LatLongGrid class should be the only subclasser of this.
** 
**	I am "pushing down" some of the intelligence (i.e. these things know about Positions
**	rather than just screen co-ordinates) as we might be getting into different projections
**	and whatnot in the future and these might not be just straight lines.
**
** This program is free software. You can use, copy and modify it under
** the terms of the GPL. See the file COPYING for the full GPL license.
**
** (c) 2000 Aquilon Technology Systems, Inc.
**
** Created: Sun Dec 31 19:38:58 EST 2000
*/

#ifndef _LATLONGLINE_H_
#define _LATLONGLINE_H_

#include "contourGraphic.h"

class LatLongLine : public ContourGraphic
{
	friend class LatLongGrid;
public:
//	LatLongLine() {}  // use the other one
	LatLongLine(const Position &p, bool lat);
	~LatLongLine();
	
protected:
	Position mPos;
	bool mLat;
	char mStr[20];
	
};



#endif
